name: ltc_vcard
description: LTC Group - Virtual Card Management App
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.0.7
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
